# Generated by Django 4.1.3 on 2022-12-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('level', models.CharField(choices=[('level 1', 'Level 1'), ('level 2', 'Level 2'), ('level 3', 'Level 3'), ('level 4', 'Level 4')], max_length=8)),
                ('bio', models.CharField(max_length=140)),
                ('hobbies', models.CharField(max_length=2048)),
                ('facebook_username', models.CharField(max_length=255)),
                ('twitter_handle', models.CharField(max_length=255)),
                ('github_username', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, upload_to='path_and_rename', verbose_name='Profile Picture')),
            ],
        ),
    ]
