# Generated by Django 4.1.3 on 2022-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=7)),
                ('level', models.CharField(choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4')], max_length=10)),
                ('semester', models.CharField(choices=[('first_semester', 'First Semester'), ('second_semester', 'Second Semester')], max_length=30)),
                ('lecturers', models.CharField(max_length=2048)),
                ('reference_text', models.CharField(max_length=2048)),
            ],
        ),
    ]
