# Generated by Django 4.1.3 on 2022-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(max_length=16)),
                ('certificates', models.CharField(max_length=256)),
                ('post', models.CharField(choices=[('assistant_lecturer', 'Assistant Lecturer'), ('junior_lecturer', 'Junior Lecturer')], max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('bio', models.CharField(max_length=140)),
                ('hobbies', models.CharField(max_length=2048)),
                ('facebook_username', models.CharField(max_length=255)),
                ('twitter_handle', models.CharField(max_length=255)),
                ('github_username', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, upload_to='path_and_rename', verbose_name='Profile Picture')),
            ],
        ),
    ]
