# Generated by Django 4.1.3 on 2022-12-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='post',
            field=models.CharField(choices=[('assistant_lecturer', 'Assistant Lecturer'), ('junior_lecturer', 'Junior Lecturer'), ('associate_lecturer', 'Associate Lecturer')], max_length=255),
        ),
    ]
