# Generated by Django 4.1.3 on 2022-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_alter_lecturer_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='post',
            field=models.CharField(choices=[('Assistant Lecturer', 'Assistant Lecturer'), ('Junior Lecturer', 'Junior Lecturer'), ('Associate Lecturer', 'Associate Lecturer')], max_length=255),
        ),
    ]
